### ISSUE TITLE
Excluding data URIs

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/gulp-css-url-rebase#3]
Hi guys,
Thanks for the plugin. As a possible enhancement:

`background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR…ftP4P7SP4N3CJZdvzoNyGq2c/HWOXJGsvVg+RA/k2MC/wN6I2YA2Pt8GkAAAAASUVORK5CYII=);`

gets rebased to:

`background-image: url(./dist/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR…ftP4P7SP4N3CJZdvzoNyGq2c/HWOXJGsvVg+RA/k2MC/wN6I2YA2Pt8GkAAAAASUVORK5CYII=);`

...could that be screened out using a regex, maybe?

Thanks again...

**Comment by balthazar** [comment]
Strange, the tests pass on this, could you please provide an example?

**Comment by jmsherry** [comment]
Hi guys,
Repo: https://github.com/jmsherry/kitchenapp
Staging: https://kitchenapp2.herokuapp.com/

Build Task: https://github.com/jmsherry/kitchenapp/blob/master/tasks/build.js

This module is all that I can see that would change the urls...

Thanks :)

**Comment by balthazar** [comment]
Oh I see,

You scaffolded your project using bangular 0.10.2. Since https://github.com/42Zavattas/generator-bangular/commit/af7420ba3e92242c85f299277af490791b757381, I've forked the original `gulp-css-rebase-urls` rebase plugin to refactor and test it. The update was landed in the 0.11.1 version, which you don't have.

You just have to `npm uninstall --save-dev gulp-css-rebase-urls && npm install --save-dev gulp-css-url-rebase`, and then update the require of the gulpfile.

**Comment by jmsherry** [comment]
Ah! Ok, awesome!! All fixed - thanks very much. :)
